services:
  - type: web
    name: my-django-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      chmod +x init.sh
      ./init.sh
    startCommand: gunicorn myproject.wsgi:application